2. Converting BCD to Hexademical
#ORG 2000H
# BEGIN 2000H
LDA 2050H		// LOADING 2 DIGIT DECIMAL FROM KEYBOARD
MOV B,A		// STORING IN REGISTER B
ANI F0H		// MASKING LAST 4 BITS TO GET MSB
RRC		// INITALLY IT IS MSB * 16 ROTATE TO MSB * 8  
MOV C,A		// STORING MSB *8 TO C
RRC 		// ROTATING RIGHT 2 TIMES TO GET MSB * 2
RRC
ADD C		// ADDING MSB * 8 + MSB * 2 TO GET MSB *10
MOV C,A		// STORING MSB * 10 HEX VALUE FOR FUTURE
MOV A,B		// GETTING ORIGINAL NUMBER 
ANI 0FH		// MASKING FIRST 4 BITS TO GET LSB
ADD C		// ADDING WITH MSB * 10 TO GET FINAL RESULT
STA 2051H		// STROING THE HEX VALUE IN 2051
HLT

# ORG 2050H
# DB 99H
