// Adding 2 4 digits BCD numbers
#ORG 2000H
#BEGIN 2000H
LXI H,2050H		//LOADING H TO MEMORY POINTER OF 1ST NO
LXI D,2052H		//LOADING D TO MEMORY POINTER OF 2ND NO
MOV A,M		//COPYING DATA TO A
MOV B,A		//COPYIG DATA TO B
LDAX D		//LOADING DATA FROM POINTER D
ADD B		//ADDING 
DAA		//ADJUSTING DECIMAL
MVI B, A0H		//STORING B=A0
CMP B		//COMPARING A AND B
JC NEXT		//IF A>A0 MEANS DECIMAL NOT ADJUSTED
ADI 60H		//ADJUSTING DECIMAL
NEXT: STA 2054H	//STORING LAST 2 DIGITS
INX D		//INCREMENT OF POINTER
INX H		//INCREMENT OF POINTER
AHEAD: MOV A,M	//COPYING DATA TO A
MOV B,A		//COPYING DATA TO B
LDAX D		//LOADING DATA FROM POINTER D	
ADC B		//ADDING WITH CARRY
DAA		//ADJUSTING DECIMAL
STA 2055H		//STORING FIRST 2 DIGITS
HLT		//END
#ORG 2050H
#DB 54H, 11H, 47H, 16H
