// Count the number of set bits in a number
#ORG 2000H
#BEGIN 2000H
LDA 2050H		//LOADING THE DATA 
MVI C, 08H		//LOOP VARIABLE
MVI B, 00H		//COUNT THE SET BIT
LOOP: RAR		//ROTATE RIGHT THROUGH CARRY 
JNC AHEAD		//JUMP ON NO CARRY
INR B		//IF CY=1 INCREASE COUNT
AHEAD: DCR C	//DECREASE LOOP VARIABLE
JNZ LOOP		//JUMP ON LOOP IF ZERO FLAG IS RESET
MOV A,B		//TRANSFER OF DATA FROM B TO A
STA 2051H		//STORING DATA
HLT		//END
#ORG 2050H
#DB 54H
