#ORG 2000H
#BEGIN 2000H
LDA 2050H		//GET THE NUMBER OF ELEMENTS IN ARRAY
MOV C,A		//STORING THE NUMBER OF ELEMENTS
LXI H, 2051H		//INITALIZE POINTER TO ARRAY ELEMENTS
MVI B,00H		//SUM=0
LOOP:
MOV A,M		//LOADING DATA
ANI 01H		//CHECKING FOR ODD
JNZ SKIP		//DON'T ADD IF ODD
MOV A,B		//COPYING CURRENT SUM
ADD M		//ADDING EVEN NUMBER
MOV B,A		//STORING NEW SUM
SKIP:
INX H		//INCREMENT OF POINTER M
DCR C		//DECREMENT OF ELEMENTS LEFT
JNZ LOOP		//IF ZER FLAG IS RESET LOOP CONTINUES
MOV A,B		//LOADING ACCUMULATOR WITH SUM
STA 3000H		//STORING SUM
HLT		//END
#ORG 2050H
#DB 04H, 02H, 43H, 13H, 06H