; Q1: SUM OF ARRAY ELEMENTS
.MODEL SMALL
.STACK 100H
.DATA
	ARR DB 5,3,1,7,9,2,6,4,8,10	;ARRAY ELEMENTS
	LEN DW $-ARR			;LENGTH OF ARRAY
	SUM DW ?			;SUM
.CODE
START:	MOV AX, @DATA
	MOV DS, AX
	MOV SI, 0
	MOV AX, 0
	MOV CX, LEN
REPEAT: MOV BL, ARR[SI]
	MOV BH, 0
	ADD AX, BX
	INC SI
	DEC CX
	JNZ REPEAT
	MOV SUM, AX
	MOV AH, 4CH
	INT 21H
	END START
.END