; Q2. AVERAGE OF ARRAY ELEMENTS
.MODEL SMALL
.STACK 100H
.DATA
	ARR DB 7,8,6,5,7,3,6	;ARRAY ELEMENTS
	LEN DW $-ARR		;LENGTH OF ARRAY
	AVG DW ?		;AVERAGE	
.CODE
START:	MOV AX, @DATA		
	MOV DS, AX
	MOV SI, 0		;LOAD OFFSET TO SI
	MOV AX, 0		;INITIALIZE SUM=0
	MOV CX, LEN		;LOOP VARIABLE
REPEAT: MOV BL, ARR[SI]		;8 BIT NUMBER
	MOV BH, 0		;FIRST 8 BITS=0
	ADD AX, BX		;ADDITION
	INC SI			;INCREMENT OF OFFSET ADDRESS
	DEC CX			;DECREMENT OF COUNT
	JNZ REPEAT		;IF ZF=0 REPEAT
	MOV DX, LEN
	DIV DL			;DIVIDING FOR AVERAGE
	MOV AVG, AX		;STORING AVERAGE
	MOV AH, 4CH		
	INT 21H
	END START
.END