; Q3. DIFFERENCE OF MINIMUM AND MAXIMUM OF ARRAY ELEMENTS
.MODEL SMALL
.STACK 100H
.DATA
	ARR DB 7,8,6,5,7,3,6	;ARRAY ELEMENTS
	LEN DW $-ARR		;LENGTH OF ARRAY
	MIN DB ?
	MAX DB ?	
.CODE
START:	MOV AX, @DATA		
	MOV DS, AX
	MOV SI, 0		;LOAD OFFSET TO SI
	MOV AL, ARR[SI]		;INITIALIZE MIN=FIRST ELEMENT
	MOV MIN,AL		;INITIALIZE MIN
	MOV MAX,AL		;INITIALIZE MAX
	MOV CX, LEN		;LOOP VARIABLE
	INC SI	
	DEC CX
REPEAT: MOV BL, ARR[SI]		;8 BIT NUMBER
	INC SI			;INCREMENT OF OFFSET ADDRESS
	DEC CX			;DECREMENT OF COUNT
	CMP MIN, AL		;COMPARE MIN and CURRENT NO. 
	JLE SKIP
	MOV MIN, AL		;[MIN]=[AL]
SKIP: 	CMP MAX, AL		;COMPARE MAX AND CUURENT NO.
	JGE NEXT		
	MOV MAX, AL		;[MAX]=[AL]
NEXT:	JNZ REPEAT		;IF ZF=0 REPEAT
	MOV AX, MAX
	SUB AX, MIN
	MOV AH, 4CH		
	INT 21H
	END START
.END