;SWAP 2 NUMBERS 
.MODEL SMALL
.STACK 100H
.DATA
	DATA1 DB 52H		;FIRST NUMBER
	DATA2 DB 29H		;SECOND NUMBER
.CODE
START:	MOV AX, @DATA		
	MOV DS, AX
	MOV AL, DATA1		;COPYING FIRST NUMBER	
	MOV AH, DATA2		;COPYING SECOND NUMBER
	MOV DATA1, AH		;COPYING 2ND TO 1ST LOCATION
	MOV DATA2, AL		;COPYING 1ST TO 2ND LOCATION
	MOV AH, 4CH	
	INT 21H
	END START
.END
	