; Binary to Gray Code Convertor
.MODEL SMALL
.STACK 100H
.DATA
	BIN  DB 07H		;BINARY NUMBER
	GRAY DB ?		;GRAY CODE
.CODE
START:	MOV AX, @DATA		
	MOV DS, AX
	MOV AL, BIN		;COPYING BINARY NUMBER
	MOV BL, BIN		;COPYING BINARY NUMBER
	SHR BL, 01		;SHIFTING BY 1 AND MSB=0
	XOR AL, BL		;XOR TO GET GRAY CODE
	MOV GRAY,AL		;STORING GRAY CODE
	MOV AH, 4CH	
	INT 21H
	END START
.END