1. FInding the COUNT of numbers divisible by 2 but not divisible by 4
#ORG 2000H
# BEGIN 2000H
LXI H, 2500H		//LOADING HL REGISTER 
MOV A,M		//COPYING [HL] TO A
MOV C,A		//COPYING NUMBER OF ELEMENTS LEFT TO C
INX H		//INCREASING M POINTER
MVI B, 00H		//COUNT OF NUMBER OF ELEMENTS
LOOP:		//LOOP 
MOV A,M		//COPYING [HL] TO A
INX H		//INCREASING MEMORY POINTER
RRC		//ROTATING RIGHT TO GET LSB IN CARRY FLAG
JC NEXT		//JUMP IF CF=1
RRC		//ROTATING RIGHT TO GET LSB IN CARRY FLAG
JNC NEXT		//JUMP TO NEXT IF CF=0
INR B		//INCREASING COUNT
NEXT: 		//NEXT
DCR C		//DECREASING COUNT OF REMAINING ELEMENTS
JNZ LOOP		//JUMP IF ZF=0 TO LOOP
MOV M,B		//STORING THE COUNT AT MEMPORY POINTER
HLT		//END OF PROGRAM
# ORG 2500H
# DB 08H, 14H, 76H, 54H, 87H, 56H, 45H, 34H, C0H
