; TEMPERATURE CONTROL USING PORT A AND PORT B OF 8255 INTERFACE
.MODEL SMALL
.STACK 64H
.CODE

START:	IN AL, 80H	;TAKING INPUT FROM PORT A
    	MOV BL,64H	;BL=64H
    	CMP AL, BL	;COMPARING AL AND BL
    	JL START	;IF AL<BL JUMP TO START
    	OUT 82H, AL	;OUTPUT TO PORT B
    	MOV AH,4CH
    	INT 21H
END START
.END