; GIVEN 2 ARRAY OF 8 BIT NUMBERS FIND SUM OF ARR[I]*PRI[I]
; PRIORITY IS UNIQUE AND IN BETWEEN 1 TO NUM INCLUSIVE
.MODEL SMALL
.STACK 100H
.DATA
	ARR DB 1,2,3,4,5,6,7,8 	;ARRAY ARR
	PRI DB 8,7,6,5,4,3,2,1	;ARRAY PRI
	NUM DB 8		;NUMBER OF ELEMENTS
	SUM DW ?		;SUM OF ARR[I]*PRI[I]
.CODE
START:	MOV AX, @DATA		;AX = DATA SEGMENT ADDRESS
	MOV DS, AX		;LOADING DS TO AX
	MOV SI, 00H		;OFFSET
	MOV DX, 00H		;SUM=0
	MOV CL, NUM		;LOOP COUNT VARIABLE
	MOV CH, 00H		;COUNT VARIABLE EXTENSION
REPEAT:	MOV AL, ARR[SI]		;LOADING NUMBER FROM ARR
	MOV BL, PRI[SI]		;LOADING NUMBER FROM PRI
	MUL BL			;AL*BL
	ADD DX, AX		;ADDING RESULT TO SUM
	INC SI			;INCREMENT OFFSET
	LOOP REPEAT		;CX=CX-1 IF CX!=0 LOOP AGAIN
	MOV SUM, DX		;STORING SUM
	MOV AH, 4CH		;RETURNING CONTROL TO OS
	INT 21H			
	END START
.END