;FINDING THE NUMBER OF UPPERCASE CHARACTERS IN A STRING
.MODEL SMALL
.STACK 100H
.DATA
	STRING1 DB 'FJGJFKRwnrrFGJTVewwcGRJV$'
	LEN 	DW	0
	NUM	DW 	0
	STRING2 DB	?
	
.CODE
START:	MOV AX, @DATA		;AX = DATA SEGMENT ADDRESS
	MOV DS, AX		;LOADING DS TO AX
	MOV ES, AX		;LOADING ES TO AX
	LEA DI, STRING1		;LOADING STARTING ADDRESS OF STRING1 TO DI
	MOV AL, '$'		;CHARACTER TO CHECK FOR END OF STRING
NEXT: 	SCASB 			;COMPARING AL WITH [DI]
	JE DONE			;IF EQUAL THEN JUMP TO DONE	
	INC LEN			;INCREMENT LENGTH OF STRING
	JMP NEXT		;JUMP BACK TO NEXT
DONE:	LEA SI, STRING1		;SOURCE POINTER
	LEA DI, STRING2		;DESTINATION POINTER
	MOV CX, LEN		;COPYING LENGTH FOR LOOP
	REP MOVSB		;COPYING ENTIRE BLOCK FROM SI TO DI
	MOV CX, LEN		;COPYING LENGTH FOR LOOP
	LEA SI, STRING2		;SOURCE POINTER
	LEA DI, STRING2		;DESTINATION POINTER
REPEAT:	LODSB			;AL=[SI] 
	OR AL, 20H		;CHANGING TO LOWERCASE
	STOSB			;[DI]=AL
	LOOP REPEAT		;REPEAT WHILE CX!=0
	LEA SI, STRING1		;SOURCE POINTER
	LEA DI, STRING2		;DESTINATION POINTER
	MOV CX, LEN		;COPYING LENGTH FOR LOOP
FOR:	CMPSB			;COMPARING [SI] AND [DI]
	JE SKIP			;IF EQUAL JUMP TO SKIP
	INC NUM			;IF NOT EQUAL INCREMENT COUNT
SKIP:	LOOP FOR		;CX=CX-1 LOOP WHILE CX!=0
	MOV AH, 4CH		;RETURNING CONTROL TO OS
	INT 21H			
	END START
.END